import {icon} from './components.mjs';

export function applicationScene(mode='qa') {
 const platform=mode==='platform';
 const phases=platform?['Open billing','Find invoice','Download','Check file']:['Open checkout','Pay','Follow webhook','Check access'];
 return `<div class="app-scene" id="interactive-demo" data-app-scene="${mode}" data-frame="0" data-outcome="working">
  <div class="scene-heading"><div class="scene-goal">${icon('cursor')}<strong>${platform?'Find September’s invoice and download the PDF.':'Buy a plan. Make sure the customer gets access.'}</strong></div><div class="scene-playback"><span>Interactive example</span><button class="scene-play" data-scene-play aria-label="Pause example">${icon('pause')}<span>Pause</span></button><button class="scene-replay" data-scene-replay aria-label="Replay example">${icon('replay')}</button></div></div>
  <div class="application-stage">
   <div class="scene-browser">
    <div class="scene-browser-top"><span class="scene-window-dots" aria-hidden="true"><i></i><i></i><i></i></span><span>northstar.test / ${platform?'invoices':'billing'}</span>${icon('lock')}</div>
    <div class="scene-browser-content">
     <div class="scene-workspace"><span class="northstar-symbol">${icon('layers')}</span><div><strong>Northstar</strong><span>${platform?'Invoices':'Workspace billing'}</span></div><span class="scene-user">Sam’s workspace</span></div>
     ${platform?`<div class="scene-invoice-heading"><strong>Invoices</strong><span>Billing history</span></div><div class="scene-invoices"><div data-invoice-row="latest"><span class="scene-file-icon">${icon('file')}</span><span>September invoice<small>Sep 01, 2026 · PDF</small></span><span data-invoice-status>Available</span></div><div><span class="scene-file-icon">${icon('file')}</span><span>August invoice<small>Aug 01, 2026 · PDF</small></span><span>Paid ${icon('check')}</span></div></div><button class="scene-app-action" data-scene-advance>Find September invoice ${icon('arrow')}</button>`:`<div class="scene-plan"><div><span>Your current plan</span><strong data-scene-plan>Free</strong></div><span class="scene-plan-pill" data-scene-access>Basic access</span></div><div class="scene-feature-check"><span>${icon('layers')} Unlimited projects</span><span class="scene-access-lock">${icon('lock')} Pro required</span><span class="scene-access-ready">${icon('check')} Available</span></div><div class="scene-payment-method">${icon('card')} <span>Test card ending in 4242</span><strong>$24 / month</strong></div><button class="scene-app-action" data-scene-advance>Upgrade workspace ${icon('arrow')}</button>`}
    </div>
   </div>
   <svg class="application-tracks" viewBox="0 0 120 300" fill="none" preserveAspectRatio="none" aria-hidden="true"><path class="track-base" d="M0 150H34Q60 150 60 124V45Q60 20 86 20H120M60 105V170Q60 195 86 195H120M60 170V250Q60 275 86 275H120"/><path class="track-active track-first" d="M0 150H34Q60 150 60 124V45Q60 20 86 20H120"/><path class="track-active track-second" d="M60 105V170Q60 195 86 195H120"/><path class="track-active track-return" d="M60 170V250Q60 275 86 275H120"/><circle class="track-origin" cx="2" cy="150" r="4"/></svg>
   <div class="scene-observations"><div class="scene-observer"><span class="scene-agent">${icon('cursor')}</span><strong>Molar is checking</strong><span data-scene-agent>Open checkout</span></div>
    <div class="scene-service scene-service-first"><span class="scene-service-icon">${icon(platform?'file':'card')}</span><div><span>${platform?'The requested document':'The payment'}</span><strong data-scene-first>${platform?'Looking for September':'Ready to charge'}</strong></div><i data-first-indicator></i></div>
    <div class="scene-service scene-service-second"><span class="scene-service-icon">${icon(platform?'download':'bolt')}</span><div><span>${platform?'The downloaded file':'The webhook'}</span><strong data-scene-second>${platform?'Waiting for invoice':'Waiting for payment'}</strong></div><i data-second-indicator></i></div>
    <div class="scene-result"><span class="scene-result-symbol" data-result-icon>${icon('cursor')}</span><div><strong data-scene-result>${platform?'Molar opens the billing page.':'Molar starts where your customer does.'}</strong><p data-scene-description>${platform?'Find the document that matches your request.':'A browser, a test account, and a real user goal.'}</p></div></div>
    ${platform?`<a class="scene-result-link" href="/platform/browser-agents">Explore browser tasks ${icon('arrow')}</a>`:`<button class="scene-condition" data-scene-condition aria-pressed="true"><span class="scene-switch" aria-hidden="true"></span><span>Delay the webhook</span><small>Try changing this</small></button>`}
   </div>
  </div>
  <div class="scene-bottom"><ol class="scene-timeline" aria-label="Example progress">${phases.map((p,i)=>`<li data-scene-phase="${i}"${i===0?' aria-current="step"':''}><span>${i+1}</span>${p}</li>`).join('')}</ol><details class="scene-evidence"><summary>Inspect result ${icon('arrow')}</summary><div><dl><div><dt>${platform?'Request':'Payment'}</dt><dd data-evidence-first>Not checked yet</dd></div><div><dt>${platform?'File':'Webhook'}</dt><dd data-evidence-second>Not checked yet</dd></div><div><dt>${platform?'Outcome':'Account access'}</dt><dd data-evidence-outcome>Not checked yet</dd></div></dl><a href="/products/trace">Explore Trace ${icon('arrow')}</a></div></details></div>
  <span class="sr-only" role="status" data-scene-announcement></span>
 </div>`;
}
