import {document} from './document.mjs';
import {esc,icon} from './components.mjs';
import {productGraphic} from './product-graphics.mjs';
import {articleGraphic} from './article-graphics.mjs';
import {askWorkspace} from './ask-workspace.mjs';

export const guideKind=article=>/download|invoice|agent|playwright-test-generation/.test(article.path)?'platform':article.category==='Integrations'?'clones':/release|merge|github|ci-cd|regression-testing/.test(article.path)?'guard':'trace';
export const readingTime=article=>Math.max(2,Math.ceil(article.body.replace(/<[^>]*>/g,' ').split(/\s+/).filter(Boolean).length/220))+' min read';
const inline=value=>esc(value).replace(/`([^`]+)`/g,'<code>$1</code>');
const dateLabel=date=>new Date(date+'T12:00:00Z').toLocaleDateString('en',{month:'long',day:'numeric',year:'numeric',timeZone:'UTC'});
export function guideCard(article,{heading='h2'}={}){return `<a class="blog-entry" data-blog-entry data-category="${esc(article.category)}" href="${article.path}"><div class="article-cover cover-${article.category.toLowerCase()}">${productGraphic(guideKind(article),{compact:true})}</div><div class="entry-meta"><span>${esc(article.category)}</span><span>${readingTime(article)}</span></div><${heading}>${esc(article.title)}</${heading}><p>${inline(article.description)}</p><span class="read-link">Read guide ${icon('arrow')}</span></a>`;}
const productNext=kind=>({clones:['Clones','Explore the service inspector','Test a payment, callback or message with service state you can inspect.','/products/clones#product-demo'],guard:['Guard','Explore a release check','See how a failed scenario connects to a release decision.','/products/guard#product-demo'],platform:['Browser agents','Give Molar a browser task','See the browser actions and result behind a task.','/platform'],trace:['Trace','Inspect a failed checkout','Follow the browser step, request and service record together.','/products/trace#product-demo']}[kind]);
export function articleDocument(article,articles=[],{draft=false}={}){
 const used=new Map(),headings=[];
 let body=article.body.replace(/<h2[^>]*>([\s\S]*?)<\/h2>/gi,(_,title)=>{
  const text=title.replace(/<[^>]*>/g,''),base=text.toLowerCase().replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'')||'section',n=(used.get(base)||0)+1;used.set(base,n);const id=base+(n>1?'-'+n:'');headings.push({id,text});return `<h2 id="${id}">${title}</h2>`;
 }).replace(/<table[^>]*>[\s\S]*?<\/table>/gi,table=>`<div class="table-scroll">${table}</div>`)
 .replace(/<pre[^>]*>[\s\S]*?<\/pre>/gi,pre=>`<div class="code-window article-code"><div class="article-code-bar"><span>Code example</span><button type="button" class="copy-button" data-copy>${icon('copy')}<span>Copy</span></button></div>${pre}<p class="copy-status sr-only" role="status"></p></div>`);
 const figure=articleGraphic(article);
 body=body.includes('</section>')?body.replace('</section>','</section>'+figure):figure+body;
 const links=headings.map(h=>`<a href="#${h.id}">${esc(h.text)}</a>`).join('');
 const related=articles.filter(a=>a.path!==article.path).sort((a,b)=>Number(b.category===article.category)-Number(a.category===article.category)||b.date.localeCompare(a.date)).slice(0,3);
 const [product,nextTitle,nextCopy,nextHref]=productNext(guideKind(article));
 return document({title:article.title+' | Molar',description:article.description,path:article.path,type:'Article',noindex:draft,datePublished:draft?undefined:article.date,dateModified:draft?undefined:article.dateModified,author:article.author?{type:'Organization',name:article.author}:undefined,section:article.category,breadcrumbs:[{name:'Molar',item:'/'},{name:'Guides',item:'/blog'},{name:article.title,item:article.path}],styles:['ask.css','editorial.css','article-graphics.css'],scripts:['ask.js','editorial.js'],body:`<main id="main" class="editorial-article">${draft?'<div class="draft-banner">Unpublished draft · check every source and example before publishing</div>':''}<section class="article-hero reading-hero"><div class="wrap"><a class="article-back" href="/blog">${icon('arrow')} All guides</a><div class="article-category">${esc(article.category)}</div><h1>${esc(article.title)}</h1><p class="article-description">${inline(article.description)}</p><div class="article-meta"><span>${esc(article.author||'Molar editorial')}</span>${draft?'<span>Draft preview</span>':`<time datetime="${article.date}">${dateLabel(article.date)}</time>`}<span>${readingTime(article)}</span>${article.dateModified?`<span>Updated ${dateLabel(article.dateModified)}</span>`:''}</div></div></section><div class="article-layout wrap"><aside class="reading-sidebar"><strong>In this guide</strong><nav aria-label="On this page">${links}</nav><a class="text-link" href="#article-question">Ask a follow-up ${icon('arrow')}</a></aside><div class="article-reading"><details class="article-mobile-toc"><summary>In this guide ${icon('chevron')}</summary><nav aria-label="Article sections">${links}</nav></details><article class="article-body">${body}</article><div class="article-next"><div><span>${product}</span><h2>${nextTitle}</h2><p>${nextCopy}</p></div><a class="button button-primary" href="${nextHref}">Explore ${product} ${icon('arrow')}</a></div><section id="article-question" class="article-question"><h2>Ask about your test.</h2><p>Describe the testing problem. Get an answer with sources you can check.</p>${askWorkspace({compact:true})}</section></div></div>${related.length?`<section class="section related-guides"><div class="wrap"><div class="section-heading"><h2>Keep reading.</h2><a class="text-link" href="/blog">All guides ${icon('arrow')}</a></div><div class="blog-grid">${related.map(a=>guideCard(a,{heading:'h3'})).join('')}</div></div></section>`:''}</main>`});
}
