import {icon,esc} from './components.mjs';
import {checkoutChapters,checkoutConditions,checkoutFrame,checkoutScreen} from './checkout-story.js';
export function checkoutStory(){
 const initial=checkoutFrame();
 return `<section class="section checkout-story" id="checkout-story"><span id="recorded-run" class="fs-old-anchor" aria-hidden="true"></span><div class="wrap"><div class="fs-heading"><h2>Payment succeeded.<br> The customer is still locked out.</h2><p>Follow a new account through signup, email verification, and checkout. See how a failed payment update can leave a paying customer without access.</p></div>
 <div class="fs-theater" data-checkout-story data-step="5" data-condition="callback" data-result="failed">
 <div class="fs-toolbar"><strong>${icon('branch')} Signup to paid access</strong><span>Interactive example</span><div><button type="button" data-story-play aria-pressed="false">${icon('play')}<span>Replay</span></button><button type="button" data-story-restart aria-label="Restart the example">${icon('replay')}</button></div></div>
 <div class="fs-chapters" role="tablist" aria-label="Explore the customer flow">${checkoutChapters.map((name,i)=>`<button type="button" role="tab" id="checkout-step-${i}" data-story-step="${i}" aria-controls="checkout-panel" aria-selected="${i===5}" tabindex="${i===5?0:-1}"><span>${i+1}</span>${name}<i aria-hidden="true"></i></button>`).join('')}</div>
 <div class="fs-stage" role="tabpanel" tabindex="0" id="checkout-panel" data-story-panel aria-labelledby="checkout-step-5">
 <div class="fs-browser"><div class="fs-browser-bar"><span>${icon('lock')} northstar.test</span><span>Sam’s account</span></div><div class="fs-browser-brand">Northstar<span>Workspace / Sam’s studio</span></div><div class="fs-screen" data-story-screen>${checkoutScreen(initial)}</div><div class="fs-cursor" aria-hidden="true">${icon('cursor')}<span>Molar</span></div></div>
 <aside class="fs-services" aria-label="Services behind this account"><div class="fs-services-title"><h3>Behind the page</h3><span>Same account. Connected state.</span></div><ol>${initial.services.map((service,i)=>`<li data-story-service="${i}" data-status="${service.status}"><span class="fs-service-icon">${icon(service.icon)}</span><div><span>${service.name}</span><strong>${service.value}</strong></div><span class="fs-service-state" aria-hidden="true"></span>${i<4?'<span class="fs-wire" aria-hidden="true"><i></i></span>':''}</li>`).join('')}</ol><div class="fs-signal"><span>${icon('search')}</span><p>Check the service update.<br>Then check the customer’s access.</p></div></aside>
 </div>
 <div class="fs-result"><div class="fs-result-copy"><span class="fs-result-icon">${icon('search')}</span><div><h3 data-story-title>${initial.title}</h3><p data-story-description>${initial.description}</p></div><span data-story-count>6 / 6</span></div><details class="fs-details" data-story-details><summary>Inspect example data <span><code data-story-request>${initial.request}</code><strong data-story-http>${initial.status}</strong></span>${icon('chevron')}</summary><pre data-story-json>${esc(JSON.stringify(initial.payload,null,2))}</pre><p>Authored request and account state for the selected step.</p></details></div>
 <div class="fs-conditions"><span>Change the test case</span><div>${Object.entries(checkoutConditions).map(([value,label])=>`<button type="button" data-story-condition="${value}" aria-pressed="${value==='callback'}">${label}</button>`).join('')}</div></div><p class="sr-only" role="status" aria-live="polite" data-story-announcement></p>
 </div><div class="fs-footnote"><p>Animated product example with sample data. Select a step or change the test case to inspect what happens.</p><div><a class="text-link" href="/products/clones">Control the test services ${icon('arrow')}</a><a class="text-link" href="/products/trace">Inspect a failure ${icon('arrow')}</a></div></div></div></section>`;
}
