import {readFileSync} from 'node:fs';
import {esc,icon} from './components.mjs';
import {cloneCatalog} from './clone-catalog.mjs';

const brands=JSON.parse(readFileSync(new URL('../assets/brands/source-manifest.json',import.meta.url))).assets;
const mark=(id,cls='')=>brands[id]?`<img class="${cls}" src="/assets/brands/${esc(brands[id].file)}" width="40" height="40" alt="" loading="lazy" decoding="async">`:icon('globe');
export const setupCommand='npx molar-agent init';
export const agentPrompt=`Set up Molar for this project using https://docs.molar.it/getting-started/for-agents and https://docs.molar.it/getting-started/install.

Run npx molar-agent init --json from the project root. Inspect existing configuration before editing it. Follow the documented CLI installation and authentication steps; ask me for any credentials or access you need and never put secrets in source files.

Once configured, check that this app loads at its local development URL. Use the documented execution mode that can reach that URL. Read the actual result and captured steps, report any failure or setup blocker, and suggest the next check. Do not claim a check passed without a completed result.`;

export function quickCommand(){return `<div class="quick-command"><span class="quick-command-label">Working in a repo?</span><div class="code-window"><code>${setupCommand}</code><button type="button" class="copy-button" data-copy aria-label="Copy project setup command">${icon('copy')}<span>Copy</span></button><span class="copy-status sr-only" role="status"></span></div><p>Initialize your project · Node.js 18+ <a href="https://docs.molar.it/getting-started/install" data-track="setup-docs">Setup guide ${icon('arrow')}</a></p></div>`}

export function agentHandoff(){return `<details class="agent-handoff"><summary>${icon('code')}<span>Let your coding agent set it up</span>${icon('chevron')}</summary><div class="agent-handoff-content"><p>Paste this into Claude Code, Codex, or Cursor from your project.</p><button type="button" class="button button-outline" data-copy-agent>${icon('copy')}<span>Copy agent prompt</span></button><p class="agent-copy-status" role="status"></p><details class="agent-prompt-preview"><summary>Read the prompt</summary><pre data-agent-prompt>${esc(agentPrompt)}</pre></details><a class="text-link" href="https://docs.molar.it/getting-started/for-agents" data-track="agent-docs">Agent setup docs ${icon('arrow')}</a></div></details>`}

// Membership / credits confirmed by the founder in this task, 2026-09-06.
export function startupPrograms(){return `<section class="startup-programs" aria-labelledby="startup-programs-title"><div class="wrap"><div class="startup-programs-intro"><h2 id="startup-programs-title">Supported by startup programs</h2><p>Building Molar with startup credits and resources from</p></div><ul>${[
 ['google-startups','Google for Startups Cloud Program','https://cloud.google.com/startup'],
 ['microsoft-startups','Microsoft for Startups','https://www.microsoft.com/en-us/startups'],
 ['aws-activate','AWS Activate','https://aws.amazon.com/startups/credits/'],
 ['razorpay-rize','Razorpay Rize','https://razorpay.com/rize/'],
].map(([id,name,href])=>`<li><a href="${href}">${mark(id)}<span>${name}</span></a></li>`).join('')}</ul></div></section>`}

export function catalogPreview(){const picks=['stripe','twilio','sendgrid','s3','github','slack','google-workspace','supabase'];return `<section class="catalog-preview"><div class="wrap catalog-preview-layout"><div><h2>Your app calls more than one service.</h2><p>Test those calls with 5 stateful services and 23 API fixture packs.</p><a class="text-link" href="/products/clones#clone-catalog" data-track="clone-catalog">Browse all 28 services ${icon('arrow')}</a></div><ul>${picks.map(id=>{const item=cloneCatalog.find(row=>row.id===id);return `<li><a href="/docs/clones/${id}">${mark(id)}<span>${esc(item.name)}</span></a></li>`}).join('')}</ul></div></section>`}

export function fullCloneCatalog(){return `<section class="section clone-catalog-section" id="product-capabilities"><div class="wrap" id="clone-catalog" data-clone-catalog><div class="catalog-heading"><h2>Find the services<br>your app depends on.</h2><p>All 28 services in the Clones catalog, with the supported operations and setup for each.</p></div><div class="catalog-coverage"><div><h3>5 stateful services</h3><p>Create and inspect records. Use supported clock, callback, snapshot, and reset controls to repeat your test.</p></div><div><h3>23 API fixture packs</h3><p>Test against predefined responses for named operations. These packs do not reproduce the provider’s full behavior or state transitions.</p></div></div><div class="catalog-controls" hidden><div class="catalog-filters" role="group" aria-label="Filter by service coverage"><button type="button" data-catalog-tier="all" aria-pressed="true">All services <span>28</span></button><button type="button" data-catalog-tier="stateful" aria-pressed="false">Stateful <span>5</span></button><button type="button" data-catalog-tier="fixture" aria-pressed="false">Fixture packs <span>23</span></button></div><label class="catalog-search">${icon('search')}<span class="sr-only">Search services or operations</span><input type="search" data-catalog-search placeholder="Search services or operations" autocomplete="off" maxlength="100"></label></div><p class="catalog-count" data-catalog-count role="status">28 services</p><ul class="catalog-list">${cloneCatalog.map(({id,name,tier,description})=>`<li data-catalog-entry data-tier="${tier}"><a href="/docs/clones/${id}"><div class="catalog-brand">${mark(id)}</div><div class="catalog-entry-copy"><div><h3>${esc(name)}</h3><span class="catalog-tier">${tier==='stateful'?'Stateful':'Fixture pack'}</span></div><p>${esc(description)}</p><span class="catalog-entry-link">View coverage & setup ${icon('arrow')}</span></div></a></li>`).join('')}</ul><div class="catalog-empty" hidden><h3>No matching services.</h3><p>Try a provider name or an operation such as “messages” or “payments”.</p><button type="button" class="button button-outline" data-catalog-reset>Clear filters</button></div><div class="catalog-foot"><p>Each service covers specific API paths. Review its documentation before adding it to your test.</p><a class="text-link" href="/contact" data-track="clone-request">Need a different service? ${icon('arrow')}</a></div></div></section>`}
