const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const A=()=>'<svg class="fv-svg" viewBox="0 0 24 24" aria-hidden="true"><path d="M3 12h17m-6-6 6 6-6 6"/></svg>';
const C=()=>'<svg class="fv-svg fv-check" viewBox="0 0 24 24" aria-hidden="true"><path d="m5 12 4 4L19 6"/></svg>';
const glyph=(name)=>`<svg class="fv-svg" viewBox="0 0 24 24" aria-hidden="true">${{mail:'<rect x="3" y="5" width="18" height="14" rx="2"/><path d="m3 6 9 7 9-7"/>',pointer:'<path d="m5 3 14 10-7 1-4 7Z"/>',search:'<circle cx="10" cy="10" r="6"/><path d="m15 15 6 6"/>',download:'<path d="M12 3v12m-5-5 5 5 5-5M5 17v4h14v-4"/>',branch:'<circle cx="6" cy="5" r="2"/><circle cx="6" cy="19" r="2"/><circle cx="18" cy="7" r="2"/><path d="M6 7v10M6 13h5a7 7 0 0 0 7-4"/>',close:'<path d="m6 6 12 12M18 6 6 18"/>'}[name]}</svg>`;
const windowDots='<span class="fv-window-dots" aria-hidden="true"><i></i><i></i><i></i></span>';
const statusDot='<i class="fv-status-dot" aria-hidden="true"></i>';
const cap=(t,n='Illustrative workflow')=>`<figcaption><span>${esc(t)}</span><small>${n}</small></figcaption>`;
const fig=(k,t,b,c)=>`<figure class="feature-visual fv-${k}${c?' is-compact':''}" data-motion-scene aria-label="${esc(t)}">${cap(t)}${b}</figure>`;
const scene=(k,body,c)=>fig(k,{checkout:'Checkout journey',identity:'Identity journey',collaboration:'Workspace collaboration',preview:'Preview check',automation:'Browser task',data:'Structured extraction',swarm:'Agent coverage',live:'Live evidence'}[k]||'Checkout journey',`<div class="fv-stage fv-${k}-stage">${body}</div>`,c);
function checkout(){return `<div class="fv-trip"><div class="fv-browser" data-motion-item style="--i:0"><div class="fv-window">${windowDots} <span>checkout.acme.test</span></div><div class="fv-card"><em>Payment</em><strong>Acme Pro plan</strong><code>4242 4242 4242 4242</code><small>08 / 28 · Test card</small></div></div><div class="fv-join">${A()}</div><div class="fv-webhook" data-motion-item style="--i:1"><em>Signed callback</em><strong>Payment webhook</strong><code>POST /webhooks/payment</code><span>${C()} signature verified</span></div><div class="fv-join">${A()}</div><div class="fv-receipt" data-motion-item style="--i:2"><b>${C()}</b><div><em>Order #1042</em><strong>Confirmed</strong><small>Receipt → test inbox</small></div></div></div><svg class="fv-lines" viewBox="0 0 900 220" preserveAspectRatio="none" aria-hidden="true"><path d="M245 110C285 48 316 48 355 110M545 110C585 172 620 172 655 110"/><path class="fv-flow" pathLength="1" d="M245 110C285 48 316 48 355 110M545 110C585 172 620 172 655 110"/></svg>`}
function identity(){return `<div class="fv-trip"><div class="fv-mini-browser" data-motion-item style="--i:0"><div class="fv-window">${windowDots} <span>acme.test / sign up</span></div><div class="fv-form"><em>Create account</em><strong>Join your workspace</strong><label>name@example.com</label><label>••••••••</label><button>Continue ${A()}</button></div></div><div class="fv-join">${A()}</div><div class="fv-envelope" data-motion-item style="--i:1"><span class="fv-mail">${glyph('mail')}</span><em>Acme · test inbox</em><strong>Verify your email</strong><small>Your code is ready to use.</small><div class="fv-otp">${'482190'.split('').map(x=>`<b>${x}</b>`).join('')}</div></div><div class="fv-join">${A()}</div><div class="fv-session" data-motion-item style="--i:2"><b>${C()}</b><em>Session</em><strong>Workspace ready</strong><small>Member identity verified</small><code>session_7f24</code></div></div><svg class="fv-lines" viewBox="0 0 900 220" preserveAspectRatio="none" aria-hidden="true"><path d="M245 110H355M545 110H655"/><path class="fv-flow" pathLength="1" d="M245 110H355M545 110H655"/></svg>`}
function collaboration(){return `<svg class="fv-lines" viewBox="0 0 900 230" preserveAspectRatio="none" aria-hidden="true"><path d="M425 105C465 57 495 57 535 105"/><path class="fv-flow" pathLength="1" d="M425 105C465 57 495 57 535 105"/></svg><div class="fv-collab"><article class="fv-pane" data-motion-item style="--i:0"><header>Owner view <b>Acme workspace</b></header><div><em>People</em><strong>Invite a teammate</strong><p>${statusDot} Priya · Owner <i>online</i></p><label>sam@example.com <button>Invite</button></label></div></article><div class="fv-invite">${A()}<small>scoped invite</small></div><article class="fv-pane" data-motion-item style="--i:1"><header>Member view <b>Sam's workspace</b></header><div><em>Access granted</em><strong>Project dashboard</strong><p class="fv-permission">${C()} Projects <small>read / write</small></p><p class="fv-permission muted">${C()} Billing <small>no access</small></p></div></article></div><div class="fv-access" data-motion-item style="--i:2"><em>Observed result</em><strong>Member access scoped correctly</strong><small>Invite accepted · state matches policy</small></div>`}
function preview(){return `<div class="fv-split"><article class="fv-pr" data-motion-item style="--i:0"><header>${glyph('branch')} <strong>Update checkout confirmation</strong><small>Pull request #48</small></header><pre><span>- status: pending</span>\n<span>+ status: confirmed</span>\n<span>+ receipt: attached</span></pre><small>commit 8e4c · 3 files changed</small></article><div class="fv-join">${A()}<small>deploy</small></div><article class="fv-deploy" data-motion-item style="--i:1"><em>Preview environment</em><code>preview.acme.test</code>${[['Signup and verification','Passed'],['Invite a teammate','Passed'],['Payment confirmation','Failed']].map((x,i)=>`<p class="${i===2?'fail':''}">${i===2?glyph('close'):C()} <span>${x[0]}</span><b>${x[1]}</b></p>`).join('')}</article></div><div class="fv-foot" data-motion-item style="--i:2">${statusDot} 3 journeys checked <span>Trace attached to the failed check</span></div><svg class="fv-lines" viewBox="0 0 900 220" preserveAspectRatio="none" aria-hidden="true"><path class="fv-flow" pathLength="1" d="M390 110H510"/></svg>`}
function automation(){return `<svg class="fv-lines" viewBox="0 0 900 230" preserveAspectRatio="none" aria-hidden="true"><path d="M245 115C300 50 350 50 410 115S510 180 565 115S650 50 705 115"/><path class="fv-flow" pathLength="1" d="M245 115C300 50 350 50 410 115S510 180 565 115S650 50 705 115"/></svg><div class="fv-split"><article class="fv-task" data-motion-item style="--i:0"><div class="fv-window">${windowDots} <span>billing.acme.test</span></div><div><em>Browser task</em><strong>Find August invoice</strong><label>${glyph('search')} Search invoices</label><p>Aug 2026 <b>Paid</b><button>Open</button></p></div></article><div class="fv-pointer" data-motion-item style="--i:1">${glyph('pointer')}</div><article class="fv-document" data-motion-item style="--i:2"><em>Document</em><strong>invoice_august_2026.pdf</strong><hr><hr><hr><small>${glyph('download')} Downloaded</small></article></div>`}
function data(){return `<div class="fv-split"><article class="fv-source" data-motion-item style="--i:0"><header>Plans <small>demo.acme.test/plans</small></header>${[['Starter','$9'],['Pro','$24'],['Business','$79']].map((x,i)=>`<p class="${i===1?'selected':''}"><span>${x[0]}</span><b>${x[1]}</b><i>monthly</i></p>`).join('')}<small>3 visible records</small></article><div class="fv-join">${A()}<small>extract</small></div><pre class="fv-json" data-motion-item style="--i:1">{\n  <b>"plan"</b>: <i>"Pro"</i>,\n  <b>"amount"</b>: <i>24</i>,\n  <b>"currency"</b>: <i>"USD"</i>,\n  <b>"interval"</b>: <i>"month"</i>\n}</pre></div><div class="fv-foot fv-success" data-motion-item style="--i:2">${C()} Structured result · source URL retained</div>`}
function swarm(){return `<div class="fv-persona-plan"><strong>One workspace. Different permissions.</strong><small>Example test plan</small></div><svg class="fv-branches" viewBox="0 0 900 60" preserveAspectRatio="none" aria-hidden="true"><path d="M450 0V20M150 60V20H750V60M450 20V60"/><path class="fv-flow" pathLength="1" d="M450 0V20M150 60V20H750V60M450 20V60"/></svg><div class="fv-persona-browsers">${[
 ['Guest','Public access','Browse plans','<div class="fv-role-plan"><b>Starter</b><span>$12 / month</span></div><div class="fv-role-plan"><b>Pro</b><span>$24 / month</span></div>','Private projects stay hidden'],
 ['Member','Project access','Acme workspace','<div class="fv-role-project"><span>Website launch</span><small>Can edit</small></div><div class="fv-role-project"><span>API gateway</span><small>Can edit</small></div>','Billing settings stay restricted'],
 ['Admin','Workspace access','People & permissions','<div class="fv-role-person"><b>PR</b><span>Priya Rao</span><small>Owner</small></div><div class="fv-role-person"><b>SC</b><span>Sam Chen</span><small>Member</small></div>','Role changes apply correctly']
].map((x,i)=>`<article class="fv-persona-browser" data-motion-item style="--i:${i}"><header><span>${x[0]}</span><small>${x[1]}</small></header><div class="fv-window"><i></i><i></i><i></i><span>acme.test</span></div><div class="fv-role-content"><strong>${x[2]}</strong>${x[3]}</div><footer>${C()}<span>${x[4]}</span></footer></article>`).join('')}</div><div class="fv-persona-note">Three example roles · actual coverage depends on your configured test plan.</div>`}
function live(){return `<div class="fv-live"><article class="fv-viewport" data-motion-item style="--i:0"><div class="fv-window">${windowDots} <span>checkout.acme.test / confirmation</span></div><div><nav><b>Acme</b><span>Plans</span><span>Workspace</span><span>Billing</span></nav><section><b>${C()}</b><strong>Order confirmed</strong><small>Receipt sent to test inbox</small><code>payment_intent.succeeded</code></section>${glyph('pointer')}</div></article><article class="fv-timeline" data-motion-item style="--i:1"><header>Run trace <b>00:08—00:10</b></header>${[['Open checkout','Screenshot captured','200'],['Confirm payment','POST /webhooks/payment','200'],['Receive receipt','Test inbox matched','ready']].map(x=>`<p><b>${C()}</b><span><strong>${x[0]}</strong><small>${x[1]}</small></span><code>${x[2]}</code></p>`).join('')}<small>${statusDot} Network and console evidence attached</small></article></div>`}
const render={checkout,identity,collaboration,preview,automation,data,swarm,live};
export function featureVisual(kind,{compact=false}={}){const k=render[kind]?kind:'checkout';return scene(k,render[k](),compact)}
