import {esc,icon,codeBlock} from './components.mjs';
import {traceSteps,tracePanel} from './product-trace.js';

const link=(href,label)=>`<a class="text-link" href="${href}">${label} ${icon('arrow')}</a>`;
export function traceStory(){
 const body=`<section class="section pt-demo-section" id="product-demo"><div class="wrap"><div class="pt-intro"><h2>The payment worked.<br>Why is the account still locked?</h2><p>Select a step to inspect its request, console message, and service state. Compare it with a passing example to find the difference.</p></div>
 <div class="pt-workbench" data-trace-example>
 <div class="pt-toolbar"><strong>${icon('trace')} Checkout → Pro access</strong><span>Interactive example</span><button type="button" data-trace-play aria-pressed="false">Replay example</button></div>
 <div class="pt-finding"><span>${icon('x')}<strong data-trace-finding>The payment passed, but the access check failed.</strong></span><button type="button" data-trace-jump>Go to failed check ${icon('arrow')}</button></div>
 <div class="pt-debugger"><nav class="pt-steps" aria-label="Steps in the example"><h3>Browser steps</h3>${traceSteps.map((step,i)=>`<button type="button" data-trace-step="${i}" aria-pressed="${i===3}"${i===3?' class="is-selected"':''}><span class="pt-step-index">${i+1}</span><span><strong>${step.label}</strong><small>${step.time}</small></span>${icon(i===3?'x':'check')}</button>`).join('')}</nav>
 <div class="pt-browser"><div class="pt-browser-address">${icon('globe')} northstar.test / billing <span data-trace-time>4.1s</span></div><div class="pt-app"><div class="pt-app-brand">Northstar <span>Example app</span></div><p>Sam’s workspace</p><h3 data-trace-screen-title>Your workspace</h3><p data-trace-screen-message>Your account is still on the Free plan.</p><div class="pt-app-plan"><span>Current plan<strong>Free</strong></span>${icon('lock')}</div><div class="pt-app-feature"><span>Shared team projects</span><strong>Pro required</strong></div></div><div class="pt-browser-caption" data-trace-current-step>Check that the account can use Pro features</div></div>
 <div class="pt-inspector"><div class="pt-tabs" role="tablist" aria-label="Inspect the selected step">${[['network','Network'],['console','Console'],['state','Service state']].map(([value,label],i)=>`<button type="button" id="trace-tab-${value}" data-trace-view="${value}" role="tab" aria-selected="${i===0}" aria-controls="trace-step-panel" tabindex="${i===0?0:-1}">${label}</button>`).join('')}</div><div class="pt-panel" data-trace-panel id="trace-step-panel" role="tabpanel" tabindex="0" aria-labelledby="trace-tab-network">${tracePanel(3)}</div><button type="button" class="pt-compare-button" data-trace-compare aria-pressed="false">${icon('layers')} Compare with a passing example</button><div class="pt-compare-panel" data-trace-compare-panel hidden><h3>Passing example · same step</h3><div data-trace-baseline>${tracePanel(3,'network',true)}</div></div></div></div>
 <div class="pt-demo-note"><span>Sample data · no connection to your app</span><span>Select steps and tabs to explore</span></div><p class="sr-only" data-trace-announcement role="status" aria-live="polite"></p></div>
 <p class="pt-example-caption">Illustrative checkout failure. Select “Receive callback,” then compare the failed request with the passing example.</p></div></section>

 <section class="section pt-investigation" id="product-capabilities"><div class="wrap"><div class="pt-section-heading"><h2>Start at the failed check.<br>Follow what happened before it.</h2><p>Trace keeps the details of a run together, so you can distinguish a broken page from a request, account, or service problem.</p></div><div class="pt-reading-grid"><article><h3>The action and the page</h3><p>Find the last successful step, then inspect the action that followed. A captured screenshot or recording shows what the browser saw. Step details identify the action and assertion, so a confirmation message does not stand in for a completed task.</p></article><article><h3>The request and response</h3><p>Inspect the captured network activity near the failure: the URL, status, timing, and available payload. A checkout can return successfully while the later account-update request fails. Follow the identifier between those requests.</p></article><article><h3>The message and the service record</h3><p>Read browser warnings and errors alongside the step. When a run includes Clones data, inspect the payment, message, or account state it recorded. The artifact list shows which service details are available for that run.</p></article></div>
 <div class="pt-diagnostic-path"><span>Payment confirmed ${icon('check')}</span>${icon('arrow')}<span>Callback failed ${icon('x')}</span>${icon('arrow')}<span>Access still missing ${icon('lock')}</span></div></div></section>

 <section class="section pt-setup" id="product-setup"><div class="wrap pt-setup-grid"><div><h2>Keep the failure close<br>to your test.</h2><p>Run the task from Molar or use your configured test integration. Open its result, select the failing step, and inspect the recordings and events that were captured.</p><ol><li>Configure the app URL, test account, and services your test needs.</li><li>Confirm which recording and request data the runner captures.</li><li>Keep the run ID with the issue or pull request so the next engineer can inspect the same result.</li></ol><p>For an existing Playwright test, record a trace and continue using its viewer. Molar does not require you to discard useful tests or recordings.</p>${link('/vs/playwright-trace','Compare the two trace viewers')}</div><div>${codeBlock('npx playwright test e2e/checkout.spec.ts --trace on\nnpx playwright show-trace path/to/trace.zip','Existing Playwright test')}${codeBlock('molar trace export TRACE_ID --format summary\nmolar trace diff PASSING_TRACE_ID FAILING_TRACE_ID --json','Molar CLI · replace IDs with your authorized traces')}<p class="pt-code-note">Molar CLI commands require sign-in and a trace your workspace can access. Available exports depend on what the run captured. See the current setup and artifact reference before automating downloads.</p>${link('https://docs.molar.it','Open the Trace documentation')}</div></div></section>

 <section class="section pt-capture-section"><div class="wrap"><div class="pt-section-heading"><h2>Know what you can inspect.</h2><p>Inspect the failed action and the requests around it. Available detail depends on your runner and capture settings.</p></div><div class="table-scroll"><table class="pt-capability-table"><thead><tr><th>Captured detail</th><th>The question it helps answer</th><th>What to check in your setup</th></tr></thead><tbody>${[
 ['Steps and assertions','Which action ran, and which condition failed?','Keep the original assertion and final run status.'],
 ['Screenshots and video','What appeared in the browser at that point?','Recording availability, playback, and retention.'],
 ['Network and console','Which request or browser error preceded the failure?','The captured time range, payload visibility, and redaction.'],
 ['Clone state','Did the payment, message, or account record change?','The specific clone and state captured by this run.'],
 ['Trace comparison','What changed between these two runs?','Comparable tasks, starting state, and both authorized trace IDs.'],
 ['Exports','Can a teammate or tool inspect the saved result?','Available formats and access to the captured artifact.'],
 ].map(row=>`<tr><th scope="row">${esc(row[0])}</th><td>${esc(row[1])}</td><td>${esc(row[2])}</td></tr>`).join('')}</tbody></table></div></div></section>

 <section class="section pt-recording"><div class="wrap pt-recording-grid"><figure><video controls playsinline preload="none" poster="/assets/browser-check/final.jpg" width="1280" height="720" aria-label="Recorded Molar browser check"><source src="/assets/browser-check/video.webm" type="video/webm">${link('/assets/browser-check/video.webm','Download the recording')}</video><figcaption>Actual controlled run · add, check, remove, check absence</figcaption></figure><div><h2>A recording you can<br>watch and inspect.</h2><p>This unedited run shows Molar adding an element, checking it appeared, removing it, and checking it was gone. Open the result to inspect the actions and checks beside the video.</p><p>The result and recording describe this four-step browser task. The checkout debugger above uses a separate, illustrated example.</p>${link('/examples/autonomous-browser-check','Read the run and its checks')}${link('/assets/browser-check/result.json','Open the recorded result')}</div></div></section>

 <section class="section pt-handoff"><div class="wrap pt-setup-grid"><div><h2>Give the next person<br>the exact starting point.</h2><p>Send the run and selected step to an authorized teammate. Include the expected behavior, the failing assertion, and the relevant captured request or service record. That is enough to begin investigating without recreating your entire environment.</p><p>Coding agents can inspect structured results through Molar’s CLI and MCP tools. Give them the relevant step or export, then check the fix with a new run.</p></div><div class="pt-handoff-example"><h3>Example issue summary</h3><dl><div><dt>Expected</dt><dd>The paid account can open shared projects.</dd></div><div><dt>Observed</dt><dd>Payment succeeded; the account remains on Free.</dd></div><div><dt>Investigate</dt><dd>Account-update error in the payment callback.</dd></div><div><dt>Next check</dt><dd>Repeat with the same test data after the fix.</dd></div></dl>${link('/platform/developer-tools','Connect your coding agent')}${link('/products/mender','Explore the repair preview')}</div></div></section>`;
 const faqs=[
 {q:'Does every run include video, network logs, and clone state?',a:'No. The available data depends on the runner, capture settings, and integrations. Inspect the artifact list for the run. An unavailable recording or empty service capture should not be treated as proof that nothing happened.'},
 {q:'Does playing a recording run my app again?',a:'No. Playback shows captured media from an existing run. Starting a new browser task or replaying a generated test executes code again and needs its own environment, accounts, and result. Generated clean replay is still under validation in beta.'},
 {q:'Can I compare a passing run with a failing one?',a:'The CLI can compare two traces your workspace is authorized to access. Use the same task and comparable starting state to make the differences meaningful. The interactive comparison above uses authored sample data.'},
 {q:'Can I use Trace alongside Playwright Trace Viewer?',a:'Yes. Keep Playwright Trace Viewer for your existing recordings. Molar Trace organizes the captured browser steps and available service details for Molar runs. Export formats depend on the artifacts that exist for that run.'},
 {q:'What should I include when reporting a failed test?',a:'Include the run ID, selected step, expected behavior, failed assertion, and relevant captured request or service record. Share through a path the recipient is authorized to access, rather than copying credentials or private payloads into an issue.'},
 {q:'Can a coding agent inspect the failure?',a:'Molar provides CLI and MCP tools for reading run results and trace details. The agent needs the configured authentication and relevant trace ID. Read the current developer documentation for the available tools.'},
 {q:'Will Trace tell me the root cause automatically?',a:'Trace provides the captured details that help you investigate. A failed assertion and preceding request can identify a useful starting point, but they do not by themselves establish the root cause. Review the app behavior and verify any proposed fix.'},
 {q:'Where do I start with a private application?',a:'Bring a reproducible task, the app environment, and an authorized test account to beta setup. We will confirm the capture and integration paths your workflow needs. You can inspect the public recording above before connecting your app.'},
 ];
 return {body,faqs};
}
