import {esc,icon,codeBlock} from './components.mjs';
import {traceSteps,tracePanel,traceTracks} from './product-trace.js';

const link=(href,label)=>`<a class="text-link" href="${href}">${label} ${icon('arrow')}</a>`;

export const TRACE_PLAYWRIGHT_CONFIG = `import { defineConfig } from '@playwright/test';

export default defineConfig({
  use: { trace: 'retain-on-failure' },
});`;
export const TRACE_COMMANDS = `molar trace export TRACE_ID --format markdown --output trace-report.md --json
molar trace diff PASSING_TRACE_ID FAILING_TRACE_ID --json`;
export const TRACE_MCP_SLICE = {trace_id:'TRACE_ID',kind:'network.response',step_id:'STEP_ID',limit:100,offset:0};
export const TRACE_MCP_DIFF = {trace_a:'PASSING_TRACE_ID',trace_b:'FAILING_TRACE_ID',dimension:'network'};

function timeline(){
 return `<div class="pt-timeline"><div class="pt-timeline-heading"><label for="trace-scrubber">Inspect a captured step</label><output for="trace-scrubber" data-trace-position>Step 4 of 4 · 4.1s</output></div><div class="pt-time-axis"><span>Step order</span><div>${traceSteps.map((step,i)=>`<span data-trace-column="${i}"${i===3?' class="is-current"':''}>${i+1}<small>${step.time}</small></span>`).join('')}</div></div><div class="pt-scrubber-row"><span aria-hidden="true">Playhead</span><input id="trace-scrubber" data-trace-scrub type="range" min="0" max="3" step="1" value="3" aria-valuetext="Step 4 of 4, Check account access, 4.1s"></div>${traceTracks.map(track=>`<div class="pt-track"><span>${track.label}</span><div>${track.values.map((value,i)=>`<button type="button" data-trace-event="${i}" data-trace-kind="${track.view}" data-trace-column="${i}" aria-pressed="${i===3&&track.view==='network'}" aria-label="Inspect ${track.label.toLowerCase()} at ${traceSteps[i].time}: ${esc(value)}" class="${i===3?'is-current ':''}${(track.view==='network'&&i===2)||(track.view==='console'&&i>=2)?'is-error':''}"><i aria-hidden="true"></i>${value}</button>`).join('')}</div></div>`).join('')}</div>`;
}

function investigationSection(){
 return `<section class="section pt-investigation" id="product-capabilities"><div class="wrap"><div class="pt-section-heading"><h2>Follow the payment.<br> Find the first visible failure.</h2><p>The last assertion tells you the account is still locked. The earlier callback tells you where to start investigating.</p></div><div class="pt-case-layout"><article class="pt-case"><h3>Why is Pro access missing?</h3><p>The payment was accepted, but the callback returned an account-update error. The final account check still returned the Free plan.</p><ol class="pt-citations"><li><button type="button" data-trace-cite="1" data-trace-kind="network"><span>1.8s</span><strong>Payment confirmed</strong><code>200 · succeeded</code>${icon('arrow')}</button></li><li><button type="button" data-trace-cite="2" data-trace-kind="network"><span>2.4s</span><strong>Callback failed</strong><code>500 · account_update_failed</code>${icon('arrow')}</button></li><li><button type="button" data-trace-cite="3" data-trace-kind="state"><span>4.1s</span><strong>Access still missing</strong><code>plan: free</code>${icon('arrow')}</button></li></ol><p class="pt-case-note">Example investigation · each reference opens the captured detail in the illustration above.</p></article><div class="pt-case-next"><h3>Check the callback handler next.</h3><p>Inspect the code and dependencies behind <code>account_update_failed</code>. The request identifies where the visible failure begins; it does not establish which line of code caused it.</p><h3>Then verify the customer result.</h3><p>After a fix, rerun from the same test account and service state. Check both callback delivery and Pro access. A successful payment alone would miss the bug again.</p>${link('/products/clones','Prepare repeatable service state')}</div></div><div class="pt-baseline"><div><h3>Compare the same flow<br> from the same starting point.</h3><p>Use a passing run with the same task, account role and test-service setup. An unrelated green run can produce an unhelpful diff.</p></div><div class="pt-diff-table"><div><span>Example comparison</span><strong>Passing</strong><strong>Failing</strong></div><div><span>Payment</span><code>Succeeded</code><code>Succeeded</code></div><div class="is-different"><span>Callback</span><code>200 · delivered</code><code>500 · failed</code></div><div class="is-different"><span>Account</span><code>Pro · access</code><code>Free · locked</code></div></div></div></div></section>`;
}

function setupSection(){
 return `<section class="section pt-setup" id="product-setup"><div class="wrap"><div class="pt-section-heading"><h2>Keep the failure.<br> Keep your existing tests.</h2><p>Start with the capture path your runner supports. Bring the run ID and its available artifacts into the investigation.</p></div><div class="pt-setup-grid"><div><h3>Already running Playwright?</h3><p>Add this option to your existing config to retain traces for failed tests. Playwright records actions, DOM snapshots, network and console activity; its viewer can inspect them locally.</p>${codeBlock(TRACE_PLAYWRIGHT_CONFIG,'playwright.config.ts · merge into your existing config')}${codeBlock('npx playwright test e2e/checkout.spec.ts --trace on\nnpx playwright show-trace path/to/trace.zip','Record a local test and open its saved trace')}<p class="pt-code-note">Replace the test and trace paths. The first command runs your test; the second opens the saved recording. These are Playwright commands, not a Molar upload.</p>${link('https://playwright.dev/docs/trace-viewer','Read Playwright’s capture guide')}</div><div><h3>Inspect a captured Molar run.</h3><ol><li>Open the run result and check its artifact list.</li><li>Use its Trace ID to export a report or compare it with an authorized passing trace.</li><li>Keep that ID and the failing assertion with the issue or pull request.</li></ol>${codeBlock(TRACE_COMMANDS,'Molar CLI · export and compare')}<p class="pt-code-note">Use the configured Molar CLI after sign-in, with your Trace API URL and workspace access. Replace all Trace IDs. Export writes a local report; it does not publish a share link. Available formats depend on the captured artifacts.</p>${link('https://docs.molar.it','Open the Trace setup docs')}<div class="pt-adapter-note"><h3>Using Cypress, Selenium or another runner?</h3><p>Confirm the supported ingestion and capture path during beta setup. A recording from another framework does not automatically include its network, DOM or test-service state.</p>${link('/contact','Discuss your test runner')}</div></div></div></div></section>`;
}

function captureBoundary(){
 return `<div class="pt-artifact-boundary"><div class="pt-artifact-list"><h3>Example artifact list</h3><dl><div><dt>Browser recording</dt><dd>Captured</dd></div><div><dt>Network events</dt><dd>Captured</dd></div><div><dt>DOM snapshot</dt><dd class="is-missing">Not captured</dd></div><div><dt>Saved sign-in state</dt><dd>${icon('lock')} Restricted access</dd></div></dl><p>Illustrative availability states; inspect the list on your actual run.</p></div><div><h3>Missing data is a limit on the investigation.</h3><p>A missing DOM snapshot does not mean the page never changed. An absent request body may reflect capture settings or redaction. Check what was retained before drawing a conclusion.</p><h3>Share the result with the right access.</h3><p>Keep credentials and private payloads out of issue descriptions. Check the workspace’s access, masking and retention settings before capturing or sharing sensitive flows.</p>${link('/security','Read about access and data handling')}</div></div>`;
}

function agentSection(){
 return `<section class="section pt-agent-section" id="trace-agent-tools"><div class="wrap"><div class="pt-section-heading"><h2>Give your coding agent<br> the relevant part of the run.</h2><p>Read the events around one step or compare two authorized traces. A focused result is easier to investigate than an entire log dump.</p></div><div class="pt-agent-grid"><div><h3>Read the failed request.</h3><p><code>molar_read_trace_slice</code> filters captured events by kind and exact step ID. This example requests up to 100 network responses.</p>${codeBlock(JSON.stringify(TRACE_MCP_SLICE,null,2),'MCP · molar_read_trace_slice')}</div><div><h3>Compare it with a passing trace.</h3><p><code>molar_diff_traces</code> compares network, assertion, clone or DOM evidence. Both Trace IDs must be accessible to the connected workspace.</p>${codeBlock(JSON.stringify(TRACE_MCP_DIFF,null,2),'MCP · molar_diff_traces')}</div></div><p class="pt-agent-note">Replace the Trace IDs and Step ID with values from your run. These tools read captured data; they do not start a browser or rerun a payment.</p>${link('https://mcp.molar.it/','Connect Molar to your coding agent')}<div class="pt-replay-boundary"><div><h3>Inspect the recording.<br> Run again to prove the fix.</h3><p>Playback revisits saved data. A new test executes against an environment and produces a separate result. Step-level execution replay needs supported snapshots and configuration; availability is confirmed during beta setup.</p>${link('/products/mender','See how proposed repairs are reviewed')}</div><ol><li><strong>Original failure</strong><span>Keep the assertion and captured events.</span></li><li><strong>Proposed fix</strong><span>Review the change and prepare test state.</span></li><li><strong>New run</strong><span>Check the customer result and compare.</span></li></ol></div></div></section>`;
}
export function traceStory(){
 const body=`<section class="section pt-demo-section" id="product-demo"><div class="wrap"><div class="pt-intro"><h2>The payment worked.<br> Why is the account still locked?</h2><p>Move through the captured steps. The page, requests, console and test-service records stay on the same step, so you can see where the flow broke.</p></div>
 <div class="pt-workbench" data-trace-example>
 <div class="pt-toolbar"><strong>${icon('trace')} Checkout → Pro access</strong><span>Interactive example · failed run</span><button type="button" data-trace-play aria-pressed="false">Replay example</button></div>
 <div class="pt-finding"><span>${icon('x')}<strong data-trace-finding>The payment passed, but the access check failed.</strong></span><button type="button" data-trace-jump>Go to failed check ${icon('arrow')}</button></div>
 ${timeline()}
 <div class="pt-debugger"><nav class="pt-steps" aria-label="Steps in the example"><h3>Browser steps</h3>${traceSteps.map((step,i)=>`<button type="button" data-trace-step="${i}" aria-pressed="${i===3}"${i===3?' class="is-selected"':''}><span class="pt-step-index">${i+1}</span><span><strong>${step.label}</strong><small>${step.time}</small></span>${icon(i>=2?'x':'check')}</button>`).join('')}</nav>
 <div class="pt-browser"><div class="pt-browser-address">${icon('globe')} northstar.test / billing <span data-trace-time>4.1s</span></div><div class="pt-app"><div class="pt-app-brand">Northstar <span>Example app</span></div><p>Sam’s workspace</p><h3 data-trace-screen-title>Your workspace</h3><p data-trace-screen-message>Your account is still on the Free plan.</p><div class="pt-app-plan"><span>Current plan<strong>Free</strong></span>${icon('lock')}</div><div class="pt-app-feature"><span>Shared team projects</span><strong>Pro required</strong></div></div><div class="pt-browser-caption" data-trace-current-step>Check that the account can use Pro features</div></div>
 <div class="pt-inspector"><div class="pt-tabs" role="tablist" aria-label="Inspect the selected step">${[['network','Network'],['console','Console'],['page','Page'],['state','Service state']].map(([value,label],i)=>`<button type="button" id="trace-tab-${value}" data-trace-view="${value}" role="tab" aria-selected="${i===0}" aria-controls="trace-step-panel" tabindex="${i===0?0:-1}">${label}</button>`).join('')}</div><div class="pt-panel" data-trace-panel id="trace-step-panel" role="tabpanel" tabindex="0" aria-labelledby="trace-tab-network">${tracePanel(3)}</div><button type="button" class="pt-compare-button" data-trace-compare aria-pressed="false">${icon('layers')} Compare with a passing example</button><div class="pt-compare-panel" data-trace-compare-panel hidden><h3>Passing example · same step</h3><div data-trace-baseline>${tracePanel(3,'network',true)}</div></div></div></div>
 <div class="pt-demo-note"><span>Sample data · no connection to your app</span><span>Select steps and tabs to explore</span></div><p class="sr-only" data-trace-announcement role="status" aria-live="polite"></p></div>
 <p class="pt-example-caption">Illustrative checkout failure. Select “Receive callback,” then compare the failed request with the passing example.</p></div></section>

 ${investigationSection()}

 ${setupSection()}

 <section class="section pt-capture-section"><div class="wrap"><div class="pt-section-heading"><h2>Know what you can inspect.</h2><p>Inspect the failed action and the requests around it. Available detail depends on your runner and capture settings.</p></div><div class="table-scroll"><table class="pt-capability-table"><thead><tr><th>Captured detail</th><th>The question it helps answer</th><th>What to check in your setup</th></tr></thead><tbody>${[
 ['Steps and assertions','Which action ran, and which condition failed?','Keep the original assertion and final run status.'],
 ['Screenshots and video','What appeared in the browser at that point?','Recording availability, playback, and retention.'],
 ['Network and console','Which request or browser error preceded the failure?','The captured time range, payload visibility, and redaction.'],
 ['Clone state','Did the payment, message, or account record change?','The specific clone and state captured by this run.'],
 ['Trace comparison','What changed between these two runs?','Comparable tasks, starting state, and both authorized trace IDs.'],
 ['Exports','Can a teammate or tool inspect the saved result?','Available formats and access to the captured artifact.'],
 ].map(row=>`<tr><th scope="row">${esc(row[0])}</th><td>${esc(row[1])}</td><td>${esc(row[2])}</td></tr>`).join('')}</tbody></table></div>${captureBoundary()}</div></section>

 ${agentSection()}

 <section class="section pt-recording"><div class="wrap pt-recording-grid"><figure><video controls playsinline preload="none" poster="/assets/browser-check/final.jpg" width="1280" height="720" aria-label="Recorded Molar browser check"><source src="/assets/browser-check/video.webm" type="video/webm">${link('/assets/browser-check/video.webm','Download the recording')}</video><figcaption>Actual controlled run · add, check, remove, check absence</figcaption></figure><div><h2>A recording you can<br> watch and inspect.</h2><p>This unedited run shows Molar adding an element, checking it appeared, removing it, and checking it was gone. Open the result to inspect the actions and checks beside the video.</p><p>The result and recording describe this four-step browser task. The checkout debugger above uses a separate, illustrated example.</p>${link('/examples/autonomous-browser-check','Read the run and its checks')}${link('/assets/browser-check/result.json','Open the recorded result')}</div></div></section>

 <section class="section pt-handoff"><div class="wrap pt-setup-grid"><div><h2>Give the next person<br> the exact starting point.</h2><p>Send the run and selected step to an authorized teammate. Include the expected behavior, the failing assertion, and the relevant captured request or service record. That is enough to begin investigating without recreating your entire environment.</p><p>Coding agents can inspect structured results through Molar’s CLI and MCP tools. Give them the relevant step or export, then check the fix with a new run.</p></div><div class="pt-handoff-example"><h3>Example issue summary</h3><dl><div><dt>Expected</dt><dd>The paid account can open shared projects.</dd></div><div><dt>Observed</dt><dd>Payment succeeded; the account remains on Free.</dd></div><div><dt>Investigate</dt><dd>Account-update error in the payment callback.</dd></div><div><dt>Next check</dt><dd>Repeat with the same test data after the fix.</dd></div></dl>${link('/platform/developer-tools','Connect your coding agent')}${link('/products/mender','Explore the repair preview')}</div></div></section>`;
 const faqs=[
 {q:'Does every run include video, network logs, and clone state?',a:'No. The available data depends on the runner, capture settings, and integrations. Inspect the artifact list for the run. An unavailable recording or empty service capture should not be treated as proof that nothing happened.'},
 {q:'Does playing a recording run my app again?',a:'No. Playback shows captured media from an existing run. Starting a new browser task or replaying a generated test executes code again and needs its own environment, accounts, and result. Generated clean replay is still under validation in beta.'},
 {q:'Can I compare a passing run with a failing one?',a:'The CLI can compare two traces your workspace is authorized to access. Use the same task and comparable starting state to make the differences meaningful. The interactive comparison above uses authored sample data.'},
 {q:'Can I use Trace alongside Playwright Trace Viewer?',a:'Yes. Keep Playwright Trace Viewer for your existing recordings. Molar Trace organizes the captured browser steps and available service details for Molar runs. Export formats depend on the artifacts that exist for that run.'},
 {q:'What should I include when reporting a failed test?',a:'Include the run ID, selected step, expected behavior, failed assertion, and relevant captured request or service record. Share through a path the recipient is authorized to access, rather than copying credentials or private payloads into an issue.'},
 {q:'Can a coding agent inspect the failure?',a:'Molar provides CLI and MCP tools for reading run results and trace details. The agent needs the configured authentication and relevant trace ID. Read the current developer documentation for the available tools.'},
 {q:'Will Trace tell me the root cause automatically?',a:'Trace provides the captured details that help you investigate. A failed assertion and preceding request can identify a useful starting point, but they do not by themselves establish the root cause. Review the app behavior and verify any proposed fix.'},
 {q:'Can I upload traces from my existing test runner?',a:'Confirm the current integration during beta setup before adding a reporter package. The Playwright setup shown here uses Playwright’s own tracing. It does not install a Molar reporter or automatically upload a trace.'},
 {q:'Does Trace promise a fixed retention period or public access?',a:'Retention and artifact availability depend on your workspace setup. Check the policy and the specific artifact before relying on long-term access. Exporting a report does not create a public link.'},
 {q:'Can Trace inspect what a browser agent did?',a:'Captured actions, outcomes and available decision summaries help explain the run. These are bounded run records, not a promise to expose a model’s private internal reasoning.'},
 {q:'Where do I start with a private application?',a:'Bring a reproducible task, the app environment, and an authorized test account to beta setup. We will confirm the capture and integration paths your workflow needs. You can inspect the public recording above before connecting your app.'},
 ];
 return {body,faqs};
}
