import {icon} from './components.mjs';

const node = (cls, symbol, title, detail) => `<div class="process-node ${cls}">${icon(symbol)}<strong>${title}</strong><span>${detail}</span></div>`;
const map = `<div class="process-map"><svg viewBox="0 0 600 280" preserveAspectRatio="none" fill="none" aria-hidden="true"><path d="M105 140H180Q200 140 200 115V70H300M200 140V210H300M380 70H430V140H495M380 210H430V140"/><path class="process-route" pathLength="1" d="M105 140H180Q200 140 200 115V70H300M380 70H430V140H495"/></svg>${node('process-origin','globe','Your app','Start with a URL')}${node('process-signup','users','Sign up','Verify the email')}${node('process-payment','card','Buy a plan','Confirm payment')}${node('process-destination','check','Open workspace','Check access')}</div>`;
const clones = `<div class="process-clone-clock"><span>${icon('replay')} Virtual time</span><strong>Trial ends → renewal begins</strong><div aria-hidden="true"><i></i><i></i><i></i><i></i><i></i><i></i></div></div><div class="process-service-records"><div>${icon('card')}<span>Payment<strong>Card declined</strong></span><code>requires_payment_method</code></div><div>${icon('bolt')}<span>Webhook<strong>Retry queued</strong></span><code>attempt: 2</code></div><div>${icon('mail')}<span>Test inbox<strong>Payment reminder</strong></span><code>1 message</code></div></div><p class="process-reset">${icon('replay')} Restore the snapshot. Try the next case.</p>`;
const guard = `<div class="process-release"><div class="process-commit">${icon('branch')}<strong>Checkout update</strong><span>Preview deployment</span><code>pull/48</code></div><div class="process-release-wire" aria-hidden="true"><i></i>${icon('arrow')}</div><div class="process-checks"><div>${icon('check')}<span>Sign in</span><strong>Passed</strong></div><div>${icon('check')}<span>Invite a teammate</span><strong>Passed</strong></div><div class="process-check-failed">${icon('x')}<span>Pay and get access</span><strong>Failed</strong></div></div></div><div class="process-review">${icon('trace')}<div><strong>Check the failure before you merge.</strong><span>The payment passed. The account stayed on the free plan.</span></div></div>`;
const trace = `<div class="process-trace"><ol><li><span>1</span><div>Open checkout<small>Browser action</small></div></li><li><span>2</span><div>Submit payment<small>Payment accepted</small></div></li><li class="process-trace-selected"><span>3</span><div>Check account<small>Expected Pro · found Free</small></div></li></ol><div class="process-request"><div>${icon('search')} Account response</div><pre><code>{
  "payment": "succeeded",
  "webhook": "pending",
  "plan": <mark>"free"</mark>
}</code></pre><p>The payment update hasn’t reached the account.</p></div></div>`;

const chapters = [
  {id:'discover',product:'Cartographer',title:'Explore signup, checkout and the screens between.',copy:'Start with your app’s URL. Explore signup, checkout, and the screens behind them, then inspect the map of what Molar reached.',output:'A map with browser steps you can inspect.',visualTitle:'From the first page to a working account',visual:map},
  {id:'services',product:'Clones',title:'Decline the card. Delay the webhook. Try again.',copy:'Decline a card. Delay a webhook. Read the email in a test inbox. Reset the supported services and run the same case again.',output:'Service records that explain what happened after the click.',visualTitle:'One account. Three connected services.',visual:clones},
  {id:'release',product:'Guard',title:'Run the checks your release depends on.',copy:'Run your configured checks against a preview or on a schedule. Open the failed check to see which customer action broke.',output:'A release check with its failure attached.',visualTitle:'The preview is ready. Is checkout?',visual:guard},
  {id:'debug',product:'Trace',title:'Find the request behind the failed check.',copy:'Follow the recorded steps and available network events. Inspect the response beside the failed assertion to understand what to fix.',output:'The step, response, and screenshot behind the result.',visualTitle:'Payment accepted. Access still missing.',visual:trace}
];

export function productProcess() {
  return `<section class="section product-process" id="products" data-product-process><div class="wrap"><div class="section-heading"><h2>Explore it. Test it.<br>Know where it broke.</h2><p>Map the app with Cartographer, control its test services with Clones, check releases with Guard, and investigate failures in Trace.</p></div><div class="process-layout"><nav class="process-nav" aria-label="Product walkthrough">${chapters.map(({id,product})=>`<a href="#product-${id}">${product}</a>`).join('')}</nav>${chapters.map((chapter,i)=>`<article class="process-chapter" id="product-${chapter.id}" style="--chapter:${i+1}"><div class="process-copy"><div class="process-connection">${icon(['map','layers','shield','trace'][i])}<span>${chapter.product}</span></div><h3>${chapter.title}</h3><p>${chapter.copy}</p><a class="text-link" href="/products/${chapter.product.toLowerCase()}">Explore ${chapter.product} ${icon('arrow')}</a></div><figure class="process-visual" aria-label="${chapter.visualTitle}"><figcaption><strong>${chapter.visualTitle}</strong><span>Illustrative example</span></figcaption><div class="process-canvas process-canvas-${chapter.id}">${chapter.visual}</div><div class="process-output">${icon('check')}<span>${chapter.output}</span></div><div class="process-progress" aria-hidden="true"><i></i></div></figure></article>`).join('')}</div></div></section>`;
}
