import {featureVisual} from './illustrations.mjs';
import {icon,esc} from './components.mjs';
const link=(href,label)=>`<a class="text-link" href="${href}">${label} ${icon('arrow')}</a>`;
const stories=[
  ['Checkout & payments','Did the payment become a confirmed order?','Test the cart, payment, callback, and receipt as one flow.','checkout','checkout-testing'],
  ['Sign-in & onboarding','Can a new customer actually get in?','Follow account creation, email verification, and the first signed-in screen.','identity','authentication-testing'],
  ['Team workflows','Does the invitation give the right access?','Check what owners, members, and guests can see and change.','collaboration','team-workflows'],
  ['Preview deployments','Does the change work before it goes live?','Run a critical flow against the preview and inspect the result.','preview','preview-deployments']
];
export function solutionStories(){return `<section class="section solution-stories"><div class="wrap"><div class="section-heading"><h2>Start with the flow<br>your customers need.</h2><p>A payment, an invitation, a first sign-in. See what a useful test looks like for your app.</p></div><div class="story-showcase" data-showcase><div class="story-selectors" role="tablist" aria-label="Choose a customer workflow" aria-orientation="vertical">${stories.map(([label,title,description,kind,path],i)=>`<button role="tab" id="story-tab-${i}" aria-selected="${i===0}" aria-controls="story-panel-${i}" tabindex="${i===0?0:-1}" data-showcase-tab="${i}"><span>${label}</span><strong>${title}</strong>${icon('arrow')}</button>`).join('')}</div><div class="story-panels">${stories.map(([label,title,description,kind,path],i)=>`<div id="story-panel-${i}" role="tabpanel" aria-labelledby="story-tab-${i}"${i?' hidden':''}>${featureVisual(kind)}<div class="story-caption"><p>${description}</p>${link('/solutions/'+path,'Explore this workflow')}</div></div>`).join('')}</div></div>${link('/solutions','Explore all solutions')}</div></section>`}
export function swarmSection(){return `<section class="section swarm-section"><div class="wrap"><div class="section-heading"><h2>Test what each user<br>can actually do.</h2><div><p>A guest shouldn’t see private projects. A member shouldn’t change billing. Plan checks across roles, devices, and account states with Molar Swarm.</p><p class="availability-note"><span class="preview-label">Preview</span> Availability is confirmed for your beta setup.</p></div></div>${featureVisual('swarm')}<div class="swarm-context"><p>Plan a guest signup, a member invitation, and an owner billing check. Confirm the roles and browser setup supported in the preview.</p>${link('/platform/swarm','Explore Swarm')}</div></div></section>`}
export function platformCapabilities(){return `<section class="section platform-capabilities"><div class="wrap"><div class="section-heading"><h2>The task is yours.<br>The browser work is Molar’s.</h2><p>Choose what you need done. Molar works through the page and brings back a result you can inspect.</p></div><div class="capability-stories"><article class="capability-story"><div><h3>Complete the work<br>behind the login.</h3><p>Download an invoice, update a record, or fill in a form. Give Molar the task, the website, and the access it needs.</p>${link('/platform/browser-agents','Meet browser agents')}</div>${featureVisual('automation')}</article><article class="capability-story"><div><h3>Turn a page<br>into useful data.</h3><p>Read the names, prices, or records you need and return them in a structure your software can use.</p>${link('/solutions/web-data-extraction','Explore data extraction')}</div>${featureVisual('data')}</article><article class="capability-story"><div><h3>See what happened.<br>Know what to do next.</h3><p>Follow the browser steps, then open a captured screenshot or request to investigate a failure.</p>${link('/platform/live-view','Explore browser recordings')}</div>${featureVisual('live')}</article></div></div></section>`}
export function solutionsHub(){const all=[...stories.map(([label,title,description,kind,path])=>({label,title,description,kind,path})),{label:'Browser automation',title:'Let the browser handle the repeat work.',description:'Forms, vendor portals, records, and downloads.',kind:'automation',path:'workflow-automation'},{label:'Web data extraction',title:'Get the information your software needs.',description:'Read pages and return structured records.',kind:'data',path:'web-data-extraction'}];return `<main id="main"><section class="reading-hero solutions-hero"><div class="wrap"><nav class="breadcrumbs" aria-label="Breadcrumb"><a href="/">Molar</a>${icon('chevron')}<span>Solutions</span></nav><h1>What do you need<br>the browser to do?</h1><p>Test the flows your customers rely on. Automate the browser work your team repeats. Start with a concrete job.</p></div></section><section class="section"><div class="wrap solution-library">${all.map(({label,title,description,kind,path})=>`<article><a class="solution-library-visual" href="/solutions/${path}" aria-label="Explore ${esc(label)}">${featureVisual(kind,{compact:true})}</a><div><h2>${title}</h2><p>${description}</p>${link('/solutions/'+path,label)}</div></article>`).join('')}</div></section></main>`}
