#!/usr/bin/env node
/**
 * Generate sitemap.xml — static pages + /docs/clones/:slug from CLONE_DOC_HOSTS.
 * Run from molar.it: node scripts/gen-sitemap.mjs
 */
import { readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const here = dirname(fileURLToPath(import.meta.url));
const siteRoot = join(here, "..");
const today = new Date().toISOString().slice(0, 10);

const cloneHostsSrc = readFileSync(join(siteRoot, "clone-docs-data.js"), "utf8");
const hostsBlock = cloneHostsSrc.match(/const CLONE_DOC_HOSTS = \{([\s\S]*?)\n\};/);
if (!hostsBlock) throw new Error("CLONE_DOC_HOSTS not found in clone-docs-data.js");
const cloneIds = [...hostsBlock[1].matchAll(/^\s{2}(?:'([^']+)'|([a-z0-9-]+)):\s+'/gm)]
  .map((m) => m[1] || m[2])
  .sort();

const staticPages = [
  { loc: "https://molar.it/", priority: "1.0", changefreq: "weekly" },
  { loc: "https://molar.it/film", priority: "0.9", changefreq: "monthly" },
  { loc: "https://molar.it/qa-agent", priority: "0.9", changefreq: "monthly" },
  { loc: "https://molar.it/docs", priority: "0.85", changefreq: "weekly" },
  { loc: "https://molar.it/thesis", priority: "0.7", changefreq: "monthly" },
  { loc: "https://molar.it/waitlist", priority: "0.6", changefreq: "monthly" },
  { loc: "https://molar.it/privacy", priority: "0.4", changefreq: "yearly" },
  { loc: "https://molar.it/terms", priority: "0.4", changefreq: "yearly" },
  { loc: "https://molar.it/vs/cypress", priority: "0.8", changefreq: "monthly" },
  { loc: "https://molar.it/vs/playwright", priority: "0.8", changefreq: "monthly" },
  { loc: "https://molar.it/vs/wiremock", priority: "0.85", changefreq: "monthly" },
  { loc: "https://molar.it/vs/checkly", priority: "0.85", changefreq: "monthly" },
  { loc: "https://molar.it/vs/playwright-trace", priority: "0.85", changefreq: "monthly" },
  { loc: "https://molar.it/integrations/github-actions", priority: "0.8", changefreq: "monthly" },
  { loc: "https://cartographer.molar.it/", priority: "0.9", changefreq: "monthly" },
  { loc: "https://clones.molar.it/", priority: "0.9", changefreq: "monthly" },
  { loc: "https://guard.molar.it/", priority: "0.9", changefreq: "monthly" },
  { loc: "https://trace.molar.it/", priority: "0.9", changefreq: "monthly" },
  { loc: "https://molar.it/changelog", priority: "0.75", changefreq: "weekly" },
  { loc: "https://molar.it/blog", priority: "0.8", changefreq: "weekly" },
  { loc: "https://molar.it/blog/test-stripe-without-real-cards", priority: "0.75", changefreq: "monthly" },
  { loc: "https://molar.it/llms.txt", priority: "0.9", changefreq: "weekly" },
  { loc: "https://molar.it/llms-full.txt", priority: "0.9", changefreq: "weekly" },
  { loc: "https://app.molar.it/", priority: "0.7", changefreq: "weekly" },
];

const clonePages = cloneIds.map((id) => ({
  loc: `https://molar.it/docs/clones/${id}`,
  priority: "0.7",
  changefreq: "monthly",
}));

const allPages = [...staticPages, ...clonePages];

const urlEntries = allPages
  .map(
    (p) => `  <url>
    <loc>${p.loc}</loc>
    <lastmod>${today}</lastmod>
    <changefreq>${p.changefreq}</changefreq>
    <priority>${p.priority}</priority>
  </url>`,
  )
  .join("\n");

const xml = `<?xml version="1.0" encoding="UTF-8"?>
<!-- GENERATED by scripts/gen-sitemap.mjs — do not edit by hand. -->
<!-- Regenerate: node scripts/gen-sitemap.mjs -->
<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">
${urlEntries}
</urlset>
`;

writeFileSync(join(siteRoot, "sitemap.xml"), xml, "utf8");
console.log(`Wrote sitemap.xml — ${allPages.length} URLs (${clonePages.length} clone docs)`);
